package viewBackend

import "html/template"

type FrontEndParams struct {
	Title                     string
	Name                      string
	Message                   string
	Message2                  string
	Message3                  string
	Path                      string
	StarredSet                map[string]bool
	UserData                  interface{}
	SessionData               map[string]string
	CurrentURL                string
	Page                      int
	CSRFToken                 template.HTML
	LoggedIn                  bool
	IsViewingPublic           bool
	UserOwnsDrop              bool
	IsTrashView               bool
	UserBio                   string
	UserPFP                   string
	AcceptedContacts          []string
	PendingIncomingContacts   []map[string]interface{}
	PendingOutgoingContacts   []map[string]interface{}
	Error                     map[string]string
	RepoList                  []string
	RepoMatches               []map[string]string
	RepoDescription           string
	RepoOwners                string
	RepoPublic                bool
	EditorFileName            string
	EditorFilePath            string
	EditorDropOwner           string
	EditorDropName            string
	EditorRepoOwner           string
	EditorRepoName            string
	EditorBackURL             string
	EditorLoadURL             string
	EditorSyncURL             string
	EditorStreamURL           string
	EditorMode                string
	EditorFileSize            int64
	EditorFileSizeLimit       int64
	EditorEditable            bool
	EditorHasInitialContent   bool
	EditorInitialVersion      int64
	EditorInitialContent      string
	DocumentEditorFileURL     string
	DocumentEditorSyncURL     string
	DocumentEditorStreamURL   string
	DocumentEditorLoadURL     string
	DocumentEditorExportURL   string
	DocumentEditorSaveAsURL   string
	DocumentEditorVersion     int64
	DocumentEditorLiveVersion int64
	DocumentEditorSavedAt     int64
	DocumentEditorDarkMode    bool
}